name: Deploy FunctionApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'Firepuma-WebPush-MicroService'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Firepuma.WebPush.FunctionApp'
  DOTNET_VERSION: '6.0'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          dotnet restore Firepuma.WebPush.Abstractions
          dotnet restore Firepuma.WebPush.Client
          dotnet restore Firepuma.WebPush.FunctionApp
          dotnet restore Firepuma.WebPush.Tests

      - name: Build FunctionApp
        run: dotnet build --configuration Release --no-restore --output ./output
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Test
        run: dotnet test --no-restore

      - name: 'Deploy FunctionApp'
        uses: Azure/functions-action@v1
        id: deploy_functionapp
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
